### ISSUE TITLE
Add right click item execution command function

### ISSUE THREAD

**Issue by yebanme** [LoneDev6/ItemsAdder#121]
Right click the item to execute the command, which can be divided into normal player execution, console execution and ignore permission execution.
Compatible durability

**Comment by LoneDev6** [comment]
it's already in the plugin
https://itemsadder.plugin.ga/plugin-usage/adding-content/item-properties/events
"interact.right"


and https://itemsadder.plugin.ga/plugin-usage/adding-content/item-properties/events/actions
"execute_commands"

```
execute_commands:
  first_example:
    command: 'tellraw {player} {"text":"wow you did something!","color":"gold"}'
    as_console: true
  second:
    command: 'help'
    as_console: false
  third:
    command: 'give {player} diamond'
    as_console: true
```


about durability check: 

```
increment_durability:
  amount: 10  
decrement_durability:
  amount: 10
```
