### ISSUE TITLE
[Suggestion] Loot by biome

### ISSUE THREAD

**Issue by spathizilla** [LoneDev6/ItemsAdder#124]
I couldn't see anything in the wiki about whether this is already possible but it would be awesome if you could define biomes that would activate the loot chance of items. That way I could for example restrict cactus fruit to only drop in desert biomes.

Perhaps even allow us to define the chance by biome.

**Comment by LoneDev6** [comment]
Will be added in the new update
```yaml
loots:
  blocks:
    my_stone_loot:
      type: STONE
      biomes:
      - MOUNTAINS
      items:
        pear:
          item: itemsadder:pear
          min_amount: 1
          max_amount: 5
          chance: 99
```
