### ISSUE TITLE
Per tool block hardness 

### ISSUE THREAD

**Issue by The-Gust** [LoneDev6/ItemsAdder#1268]
### Discord tag (optional)

Gust#1337

### Describe the solution you'd like

Suggestion is simple - possibility to add different hardness level of blocks for tools.

### Is your feature request related to a problem?

Suggestion based on a little "bug". When you break any block type - it's breaking with differently speed, axe and shovel breaks REAL_NOTE blocks much faster, than pickaxe, but hardness is the same for all tools types and here's not possible to make it different. 

### Describe alternatives you've considered

1) Make possibility to choose hardness only for groups of tools (- AXE, - PICKAXE, - SHOVEL, - SHEARS, etc):
```
    hardness_list:
    - PICKAXE:3
    - AXE:10   
```

2) Add for both, and for groups, and for every tool, which will looks familiar with whitelist/blacklist breaking tools in config:
```
    break_tools_blacklist:
    - WOODEN_PICKAXE
    break_tools_whitelist:
    - PICKAXE
    - pickax
    - AXE
  
    hardness_list:
    - DIAMOND_AXE:5
    - DIAMOND_PICKAXE:1
    - PICKAXE:3
    - AXE:10   
```

**Comment by razorrider7** [comment]
Any chance this is going to be added? This feature would be amazing and is much needed for what I want to do with my server...

**Comment by LoneDev6** [comment]
I think a multiplier would be better.
Anyway why cannot you pre-enchant the item with `DIG_SPEED`?
It's a more vanilla-like behaviour.

**Comment by Yurinann** [comment]
> I think a dig seed multiplier for each custom item would be better.
> 
> Anyway why cannot you pre-enchant the item with `DIG_SPEED`? It's a more vanilla-like behaviour.

I saw #1033 , but in fact I still don't fully understand how this is achieved. Should I give each square its own new tool and add them when judging events to create their own way of judging hardness for each square?

If you can provide a more detailed example, thank you very much.

**Comment by LoneDev6** [comment]
#1033 example was achieved by creating an item which will apply `FAST_DIGGING` potion effect to the player when they hold the item and remove it once they un-hold it.
It's another approach but works good.

**Comment by LoneDev6** [comment]
https://github.com/PluginBugs/Issues-ItemsAdder/issues/1498

**Comment by LoneDev6** [comment]
This is what @The-Gust suggested:
```yml
    break_tools_blacklist:
    - WOODEN_PICKAXE
    break_tools_whitelist:
    - PICKAXE
    - pickax
    - AXE
  
    hardness_list:
    - DIAMOND_AXE:5
    - DIAMOND_PICKAXE:1
    - PICKAXE:3
    - AXE:10   
```

This is what I'd write instead:
```yml
    break_tools_blacklist:
    - WOODEN_PICKAXE
    break_tools_whitelist:
    - PICKAXE
    - pickaxe
    - AXE
    break_conditions:
      DIAMOND_AXE:
        enabled: false
        hardness: 2
      DIAMOND_PICKAXE:
        hardness: 1
      "iasurvival:ruby_pickaxe":
        hardness: 0.5
      PICKAXE:
        hardness: 3
      AXE:
        hardness: 10
```
So that in the future I might add some other rules and not only hardness.

What do you think?
