### ISSUE TITLE
[BUG] Philosopher Stone can't fix

### ISSUE THREAD

**Issue by R-Josef** [LoneDev6/ItemsAdder#146]
**Describe the bug**
Philosopher Stone can not fix at crafting table, it will become dirt.

**To Reproduce**
1. open a crafting table
2. put philosopher stone and the ball into it.
3. you will get an dirt

**Screenshots**
![https://fengshuai.oss-cn-shenzhen.aliyuncs.com/%E5%9B%BE%E5%BA%8A/philosopher_stone_bug.png](https://fengshuai.oss-cn-shenzhen.aliyuncs.com/%E5%9B%BE%E5%BA%8A/philosopher_stone_bug.png)

**Info (please complete the following information):**
 - Server version: tuinity 1.15.2
 - Client version: vanilla
 - Plugin version: 2.0.9

**Comment by LoneDev6** [comment]
Please try on 2.0.11 after update, I don't experience this problem in 2.0.11 new update.
I will publish it later.

Reopen this issue if you still have the problem after update, thanks

**Comment by R-Josef** [comment]
i updated 2.0.12, this problem is still.

**Comment by LoneDev6** [comment]
Put a lot of energy orbs in the crafting table, you have to use a lot of them to charge it.
Please make a video

**Comment by R-Josef** [comment]
```yaml
    philosopher_stone_1:
      enabled: true
      permission: itemsadder.philosopher_stone
      pattern:
      - XXX
      - XPE
      - XXX
      ingredients:
        P: itemsadder:philosopher_stone
        E: itemsadder:energy_orb
      result:
        item: DIRT
        amount: 1
      return_items:
        increment_durability:
          philosopher_stone:
            item: philosopher_stone
            amount: 1
```
i just checked my config, it's include `result` and `return_items`, this is strange, it looks the same meaning, is that wrong?
