### ISSUE TITLE
[BUG] TILE type block with custom model doesn't render

### ISSUE THREAD

**Issue by Golshr** [LoneDev6/ItemsAdder#158]
**Describe the bug**
When I use the TILE block model type instead of the REAL type, it doesn't render properly

**To Reproduce**
Here is my block declaration : 
```yml
  nuclear_waste:
    display_name: nuclear_waste
    resource:
      material: STONE
      generate: false
      model_path: blocks/nuclear_waste
    specific_properties:
      block:
        placed_model:
          type: TILE
          break_particles: BLOCK
```
Block is ok when type is REAL
Please note that it doesn't work even when the blocks shape is a cube inherited from minecraft default models.

**Screenshots**
https://i.imgur.com/5h4JVTI.jpg

**Info (please complete the following information):**
 - Server version: Spigot 1.15.2
 - Client version: Vanilla 1.15.2
 - Plugin version: 2.0.9
