### ISSUE TITLE
[BUG] demoniac hammer

### ISSUE THREAD

**Issue by 100petr** [LoneDev6/ItemsAdder#212]
**Describe the bug**
When destroyed with a demoniac hammer, only one to two blocks will drop

**To Reproduce**
1. Destroy blocks with demoniac hammer
2. it will make a 3 * 3 hole (thats is ok)
3. of the 9 destroyed blocks, only one or two will drop

**Expected behavior**
All blocks will drop (9)

**Screenshots**

**Info (please complete the following information):**
 - Server version: paper 1.15.2
 - Client version: optifine 1.15.2
 - Plugin version: 2.0.18

**Additional context**

**Comment by LoneDev6** [comment]
enchant your hammer with silktouch
hammer will drop only the center block of 3x3 area.
or set  need_silk_touch: false

```
      block_break:
        multiple_break:
          keep_ores: true
          drop_all_blocks:
            enabled: true
            need_silk_touch: true
          size: 3
          depth: 3
```
