### ISSUE TITLE
[BUG] Bucket Fill event and custom durability don't work

### ISSUE THREAD

**Issue by YoutubeNosios** [LoneDev6/ItemsAdder#215]
**Describe the bug**
The event bucket_fill doesnt work and the custom durability dont work for buckets

**To Reproduce**
Add bucket_fill event and custom durability on a bucket

**Expected Action**
Do the actions associated action with the bucket_fill event and add a durability bar to it

**Info**
 - Server version: Spigot 1.15.2
 - Client version: 1.15.2
 - Plugin version: 2.0.19

**Comment by LoneDev6** [comment]
> bucket_fill

Please provide the config of your item so I can check what you mean.
Thanks

**Comment by YoutubeNosios** [comment]
Hey ! There is my item :
And can you add an option to cancel the event please ?
https://hasteb.in/gapihamu.yaml

**Comment by LoneDev6** [comment]
> 
> 
> Hey ! There is my item :
> And can you add an option to cancel the event please ?
> https://hasteb.in/gapihamu.yaml

Thanks I will publish an update today that fixes the event as now it's not called because of a bug.
This is how to properly configure your infinite bucket after the update:
```Yaml
  infinite_bucket_full:
    display_name: Infinite Bucket Full
    permission: 'adamod.items'
    resource:
      material: WATER_BUCKET
      generate: true
      textures:
      - item/infinite_bucket_full.png
    durability:
      usages: 5
    events:
      bucket_empty:
        cancel: true
        decrement_usages:
          amount: 1
        replace_near_blocks:
          radius:
            x: 1
            y: 1
            z: 1
          from: AIR
          to: WATER
  infinite_bucket:
    display_name: Infinite Bucket
    permission: 'adamod.items'
    resource:
      material: BUCKET
      generate: true
      textures:
      - item/infinite_bucket.png
    events:
      bucket_fill:
        cancel: true
        give_item:
          item: infinite_bucket_full
          amount: 1
        decrement_amount:
          amount: 1
```

**Comment by YoutubeNosios** [comment]
I don't want a full bucket , the infinite bucket is made to remove water infinitely , but thank you for publishing an update !

**Comment by LoneDev6** [comment]
> 
> 
> I don't want a full bucket , the infinite bucket is made to remove water infinitely , but thank you for publishing an update !

ahhh okay, well it's easy then:

```yaml
  infinite_bucket:
    display_name: Infinite Bucket
    permission: 'adamod.items'
    resource:
      material: BUCKET
      generate: true
      textures:
      - item/infinite_bucket.png
    durability:
      usages: 5
    events:
      bucket_fill:
        cancel: true
        decrement_usages:
          amount: 1
```
