### ISSUE TITLE
World populator option to generate ores only when there's no air exposure like vanilla

### ISSUE THREAD

**Issue by Replaycchi** [LoneDev6/ItemsAdder#2551]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [X] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Describe the solution you'd like

An option for world populator to generate ores only when there's no air exposure like vanilla.

### Is your feature request related to a problem?

I've made a custom ore and i want to make it vanilla like

### Describe alternatives you've considered

```
worlds_populators:
  test_ore:
    block: test:test_ore
    worlds:
      - Ressource
    replaceable_blocks:
      - STONE
    chunk_chance: 5
    max_height: 45
    min_height: -50
    vein_blocks: 2
    chunk_veins: 2
    **no_air_exposure: true**
```
