### ISSUE TITLE
Item Command Events

### ISSUE THREAD

**Issue by MothGirlMusic** [LoneDev6/ItemsAdder#26]
not sure if this is a bug with {player} placeholder or maybe i typed something wrong somewhere.. [but it all works with crafting, using the command works fine if i do type it out myself and all that] smelting works. but when you eat it, it doesn't seem to fire the command. here is the item:
```
mothdust:
   enabled: true
   permission: mothdust
   model_id: 100
   name: '&fMoth Dust'
   events:
      eat:
         execute_command:
            as_console: true
            command: 'cmi flightcharge add {player} 50'
   smelting:
      enabled: true
      ingredient: mofflet
      amount: 1
```
and here's the console. no errors.

![](https://cdn.discordapp.com/attachments/533413171403292712/605791893221015593/Screen_Shot_2019-07-30_at_11.57.35.png)

[i gave it to myself and ate it]
latest IA version with 1.14.4 latest spigot [the literal latest that just came out this morning]
i made other custom food that just give hunger or potion effects, etc.. they all work. its only this command one that doesnt actually seem to fire the command.. or if it does, doesn't seem to understand the placeholder? or maybe the wiki is just outdated or something
so idk if its a bug or maybe i've typed the as_console or something else wrongly
as for the command itself i've litterally copypasted it after having tabbed it out... only manual editing i did was change my name to {player} instead. [as per the wiki] so i can assure you it is correct

**Comment by MothGirlMusic** [comment]
Just changed it to his.. but that doesn't seem to work either.
```
mothdust:
   enabled: true
   permission: mothdust
   model_id: 100
   name: '&fMoth Dust'
   events:
      right_click:
         execute_command:
            as_console: true
            command: 'cmi flightcharge add {player} 50'
         reduce_amount: 1
   smelting:
      enabled: true
      ingredient: mofflet
      amount: 1
```
