### ISSUE TITLE
[Suggestion] Ore can drop exp

### ISSUE THREAD

**Issue by Command1264** [LoneDev6/ItemsAdder#276]
**Is your feature request related to a problem? Please describe.**
ore can't drop exp

**Describe the solution you'd like**

loots:
  blocks:
    end_diamond_ore:
      enabled: true
      type: itemsadder:end_diamond_ore
      items:
        DIAMOND:
          item: DIAMOND
          min_amount: 2
          max_amount: 5
          chance: 100
        EXP:
          item: EXPERIENCE_ORB
          min_amount: 2
          max_amount: 5
          chance: 100
        

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/50344708/83356039-eb382000-a395-11ea-9602-1df0c12a3a31.png)
![image](https://user-images.githubusercontent.com/50344708/83356050-fe4af000-a395-11ea-8016-0f03fb402e27.png)

**Comment by LoneDev6** [comment]
Will be added in the new update
```yaml
  blocks:
    my_stone_loot:
      type: STONE
      biomes:
      - MOUNTAINS
      items:
        pear:
          item: itemsadder:pear
          min_amount: 1
          max_amount: 5
          chance: 99
      exp:
        exp_1:
          min_amount: 1
          max_amount: 20
          chance: 99
```
