### ISSUE TITLE
[BUG] Mysterios hood

### ISSUE THREAD

**Issue by 100petr** [LoneDev6/ItemsAdder#297]
**Describe the bug**
Mysteris hood dones nott have unluck effect.

**To Reproduce**
1. Get mysterios hood
2. You have night vision, but the unluck effect does not

**Expected behavior**
I will have night vision and unluck.

**Screenshots**
![2020-06-10_15 19 24](https://user-images.githubusercontent.com/29830635/84272525-d134d500-ab2d-11ea-9390-5945392e74f7.png)

**Info (please complete the following information):**
 - Server version: paper 1.15.2
 - Client version: optifine 1.15.2
 - Plugin version: 2.0.26

**Additional context**
Also tested on your server, where there is also no unluck effect in hood.

**Comment by LoneDev6** [comment]
try it on a clean server, probably i fixed it in a previous update but i didn't syncronize my test server.

thanks

**Comment by 100petr** [comment]
I deleted everything except the configuration, I had it create new files and the effect still doesn't exist.
![2020-06-22_14 32 17](https://user-images.githubusercontent.com/29830635/85287888-33c69300-b495-11ea-87aa-a5427e8bf00b.png)

**Comment by LoneDev6** [comment]
Thanks a lot,
here's the fixed version, I ordered events in the wrong order so the plugin removes the potion effect after it applied it:
```
    events:
      wear:
        play_sound:
          name: itemsadder:ambient.creepy
          volume: 1
          pitch: 1
        remove_potion_effect_1:
          type: UNLUCK
        potion_effect:
          type: NIGHT_VISION
          duration: 1000000
          amplifier: 0
        potion_effect_2:
          type: UNLUCK
          duration: 1000000
          amplifier: 0
        play_particle:
          name: ENCHANTMENT_TABLE
      unwear:
        play_sound:
          name: itemsadder:ambient.creepy
          volume: 1
          pitch: 1
        remove_potion_effect_2:
          type: UNLUCK
        potion_effect:
          type: UNLUCK
          duration: 100
          amplifier: 0
        decrement_durability:
          amount: 10
        remove_potion_effect:
          type: NIGHT_VISION
        play_particle:
          name: ENCHANTMENT_TABLE
```
