### ISSUE TITLE
[Suggestion] Prevent multiple types of seeds from appearing at the same time

### ISSUE THREAD

**Issue by yebanme** [LoneDev6/ItemsAdder#317]
**Is your feature request related to a problem? Please describe.**
When the grass is broken, there is a certain probability of dropping seeds, but sometimes multiple seeds appear at the same time,It doesn't seem logical

**Describe the solution you'd like**
There is only one type of seed when grass is destroyed
In the following example, suppose  appears tomato_seeds, then garlic_seeds and rice_seeds no longer allows computation

**Additional context**
```
grass:
      type: GRASS
      items:
        tomato_seeds:
          item: itemsadder:tomato_seeds
          min_amount: 1
          max_amount: 2
          chance: 5
        garlic_seeds:
          item: itemsadder:garlic_seeds
          min_amount: 1
          max_amount: 2
          chance: 5
        rice_seeds:
          item: itemsadder:rice_seeds
          min_amount: 1
          max_amount: 2
          chance: 10
```

**Comment by LoneDev6** [comment]
In other words: you'd prefer me to remove seeds drops from grass?
Because I have no other idea on where to drop these seeds and randomizing more seeds drops from grass was the only solution that I come up with

**Comment by yebanme** [comment]
> In other words: you'd prefer me to remove seeds drops from grass?
> Because I have no other idea on where to drop these seeds and randomizing more seeds drops from grass was the only solution that I come up with

It seems like a solution, anyway, we only need to give players one of all the seeds, whether it's wheat or something else

**Comment by LoneDev6** [comment]
you can set chance to 0 in order to disable these, I don't see why I have to change this in the main plugin.
Thanks for the suggestion anyway

**Comment by yebanme** [comment]
We seem to have misunderstood each other,I mean, like in the configuration, when the grass is broken, sometimes all the seeds appear,It's going to feel incredible,
can we randomly drop only one type of seed instead of multiple

`grass:
      type: GRASS
      items:
        tomato_seeds:
          item: itemsadder:tomato_seeds
          min_amount: 1
          max_amount: 2
          chance: 50
        garlic_seeds:
          item: itemsadder:garlic_seeds
          min_amount: 1
          max_amount: 2
          chance: 50
        rice_seeds:
          item: itemsadder:rice_seeds
          min_amount: 1
          max_amount: 2
          chance: 50`

**Comment by LoneDev6** [comment]
Oohhh, so this is a bug report, I mean, it feels strange that sometimes it drops every item instead of only one.
Well.. mh, I have to think about how to fix/change this behaviour because making only one item drop would make them more rare

**Comment by LoneDev6** [comment]
next update preview:


- added new property drop_only_first in loots. This allows you to stop the plugin from dropping each of the items that succeed into extracting a 
correct chance to be dropped. WARNING: this would make your items harder to be dropped.
https://itemsadder.plugin.ga/plugin-usage/adding-content/loots
Example:
```yml
loots:
  blocks:
    DIAMOND_BLOCK:
      type: DIAMOND_BLOCK
      drop_only_first: true
      items:
        ruby:
          item: itemsadder:ruby
          min_amount: 1
          max_amount: 2
          chance: 80
        crystal:
          item: itemsadder:crystal
          min_amount: 1
          max_amount: 2
          chance: 10
        knowledge_fragment:
          item: itemsadder:knowledge_fragment
          min_amount: 1
          max_amount: 2
          chance: 15
```
