### ISSUE TITLE
Use `interaction` entity to handle furniture hitboxes

### ISSUE THREAD

**Issue by LoneDev6** [LoneDev6/ItemsAdder#3193]
https://minecraft.fandom.com/wiki/Interaction

Suggested here: #2458

### Interaction Entity

The new [Interaction Entity](https://minecraft.fandom.com/wiki/Interaction) can be used as an alternative for hitboxes. This would be very efficient.

Instead of raycasting and checking if raycast is intersecting with hitbox, we can now just spawn an interaction entity with correct width and height. Then we can just listen for any interaction or attack event to recognize if player broke furniture or only interacted with it.

#### Advantages:
- Very efficient
- You can set any size on interaction entity

#### Disadvantages:
- The scroll click (creative pick item) won't work anymore because client does not send any packet on scroll click an interaction entity.
- You can only set `width` and `height` without `length`

So we can leave the choice to the owner of a server by adding to the furniture config an option to select a hitbox type under `behaviours.furniture.hitbox.type` like this:
```yml
info:
  namespace: testnamespace
items:
  test_furniture:
    display_name: "Test Furniture That Uses Item Display"
    resource:
      material: PAPER
      generate: false
      model_path: test_furniture
    behaviours:
      furniture:
        entity: item_frame
        hitbox:
          type: interaction_entity # raycast, interaction_entity
          width: 1
          height: 1.5
```
