### ISSUE TITLE
[BUG] Multiple break won't drop blocks

### ISSUE THREAD

**Issue by Soldier233** [LoneDev6/ItemsAdder#360]
**Describe the bug**
The plugin enables pickaxe to destroy more than one block at a same time.
But the blocks destroyed besides the original block won't drop any item.

**To Reproduce**
None

**Expected behavior**
Fixed

**Screenshots**

**Info (please complete the following information):**
 - Server version: paper 1.16.1
 - Client version: 1.16.1
 - Plugin version: 2.0.41

**Additional context**
```
      block_break:
        multiple_break:
          keep_ores: true
          drop_all_blocks:
            enabled: true
            need_silk_touch: true
          size: 3
          depth: 1
```
