### ISSUE TITLE
[BUG] How i activate the ores?

### ISSUE THREAD

**Issue by MaskyLedOn** [LoneDev6/ItemsAdder#368]
Hy why the new Ores only the admin can see them.. or use them?? how can i make my world regenerate that new ores on map for everyone from my server???

**Comment by LoneDev6** [comment]
You have to create a world populator, there are some examples in items_packs\itemsadder\blocks.yml file, check at the very bottom of the file.
You have to create your own namespace https://itemsadder.plugin.ga/plugin-usage/adding-content/creating-your-namespace
then add the worlds_populators part and specify a populator for each block. This tells the plugin where to spawn ores and how many.

```
worlds_populators:
  ruby_ore:
    block: itemsadder:ruby_ore
    worlds:
    - world
    replaceable_blocks:
    - STONE
    - DIRT
    - ANDESITE
    - GRANITE
    - COBBLESTONE
    - GRAVEL
    chance: 70.0
    max_height: 45
    min_height: 25
    amount: 6
    iterations: 1
  spinel_ore:
    block: itemsadder:spinel_ore
    worlds:
    - world
    replaceable_blocks:
    - STONE
    - DIRT
    - ANDESITE
    - GRANITE
    - COBBLESTONE
    - GRAVEL
    chance: 90.0
    max_height: 45
    min_height: 35
    amount: 6
    iterations: 1
```
