### ISSUE TITLE
Itemsadder (DropExp on hammers not working as intended)

### ISSUE THREAD

**Issue by AcesGamingUK** [LoneDev6/ItemsAdder#383]
**Describe the bug**
i seem to have an issue with Hammers And Drop EXP
```yml
        drop_exp:
          chance: 50
          min_amount: 1
          max_amount: 5
```

when the XP bar fills instead of rolling over to the next level, it just resets the level,
Pickaxe works as expected

**To Reproduce**
Steps to reproduce the behaviour:
1. Get any hammer with Exp Drops enabled
2. break blocks,

**Expected behavior**
XP bar to increase in levels 

**Screenshots**
https://drive.google.com/file/d/1Ny8q0kTAEQkMP6ZZdWUuWTwHKIuF_pwo/view

**Info (please complete the following information):**
 - Server version: Paper version git-Paper-197 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
 - Client version: Vanilla 1.16.3
 - Plugin version: version 2.0.46
