### ISSUE TITLE
Incorrect Hitbox Alignment for Furniture Based on World Direction

### ISSUE THREAD

**Issue by Deeedline** [LoneDev6/ItemsAdder#4063]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### What happened?

Issue Description:
When adding a furniture item with a 2x2x2 hitbox in the ItemsAdder plugin, the model rotates correctly according to the world direction (e.g., north, south, east, west). However, the hitbox associated with the furniture remains fixed in the same direction regardless of the model's rotation. This results in inconsistent behavior where players can walk through the furniture or encounter invisible barriers in the wrong places.

In the attached image:

The arrow indicates the direction I was facing when placing the block.
The green dot represents the position of the armour_stand that manages the furniture model.

### Steps to reproduce the issue

Steps to Reproduce:

Create a furniture model with a 2x2x2 hitbox.
Load the model into ItemsAdder.
Place the furniture in the Minecraft world and rotate it to any world direction.
Observe that while the model rotates correctly, the hitbox remains oriented in the same direction.
Expected Behavior:
The hitbox should rotate along with the model to align with its orientation according to the world direction.

Current Behavior:
The hitbox remains static, not rotating with the model, leading to collision issues and inconsistency in gameplay.

### Server version

Purpur version 1.21.1-2324-ver/1.21.1@e12a4de

### ItemsAdder Version

ItemsAdder v4.0.2-beta-release-12

### ProtocolLib Version

ProtocolLib v5.3.0-SNAPSHOT-732

### LoneLibs Version

LoneLibs v1.0.59

### Full Server Log

https://mclo.gs/0hQ9r34

### Problematic items yml configuration file (optional)

```yaml
info:
  namespace: myitems_furnitures
items:
  custom_furnace:
    display_name: "custom_furnace"
    permission: myitems.decorative.custom_furnace
    lore:
    - lore-decorative-item
    resource:
      material: PAPER
      generate: false
      model_path: custom_furnace
    behaviours:
      furniture:
        opposite_direction: true
        fixed_rotation: true
        entity: armor_stand
        #light_level: 15
        solid: true
        hitbox:
            height: 2
            length: 2
            width: 2
        placeable_on:
          floor: true
          ceiling: false
          walls: false
        sound:
          place:
            name: block.metal.fall
          break:
            name: block.metal.break
```

### Screenshots/Videos (you can drag and drop files or paste links)

![bug](https://github.com/user-attachments/assets/8151fdac-6af1-4887-9678-a3cf62c508b5)
