### ISSUE TITLE
Block breaking issues

### ISSUE THREAD

**Issue by TheMGRF** [LoneDev6/ItemsAdder#42]
To me it is looking increasingly like "break_tools_blacklist" isn't actually working? I've specified partial names and full names and it still doesn't seem to work. I also wanted to use this issue to ask if it is intentional that you can now break every custom block with an empty hand or wrong tool) and it just disappears? Would be useful to have the original "You require x to mine this block" due to how fast mushroom blocks are to break and how people dont really know what tools to use.

**Comment by LoneDev6** [comment]
can you share an example of item? include all attributes, thanks

**Comment by TheMGRF** [comment]
```yml
blue_grass:
  enabled: true
  permission: default
  model_id: 14
  name: '&fBlue Grass'
  specific_properties:
    break_tools_blacklist:
      - PICKAXE
    cancel_drop: true
    drop_on_silktouch: false
```

I also suspect things might not be fully taking effect using /iareload but not 100% on that.

**Comment by LoneDev6** [comment]
With break_tools_blacklist you're only adding pickaxes to blacklist, so users will be able to break block with every other item but not pickaxes.

Which items you want user to use in order to break this block?

**Comment by TheMGRF** [comment]
Ideally only a shovel, so I've used this:
```yml
blue_grass:
  enabled: true
  permission: default
  model_id: 14
  name: '&fBlue Grass'
  specific_properties:
    break_tools_whitelist:
      - SHOVEL
    cancel_drop: true
    drop_on_silktouch: false
```
and that drops the item when mined with a shovel but if a player uses anything but a shovel it just breaks the block and drops nothing. This might be intended (like vanilla functionality) but I and others found it a tad weird considering these aren't vanilla blocks xD)
