### ISSUE TITLE
Cooldown Title not disappearing after a few seconds

### ISSUE THREAD

**Issue by 00Hrtz** [LoneDev6/ItemsAdder#4293]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [X] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### Discord Username (optional)

00_Hrtz

### What happened?

Hi, a while ago you implemented the feature were a cooldown title shown on screen could disappear after a few seconds and would reappear then disappear if clicked again and again. So it the cooldown was for longer periods of time it wouldn't linger on screen. It's no longer disappearing on screen in 4.0.6

https://github.com/PluginBugs/Issues-ItemsAdder/issues/3214

Not a major issue but nice if it would disappear again in the future like was shown in your video linked above.

### Steps to reproduce the issue

Click furniture or block with an event that has a Cooldown set for say 3 minutes and watch it stay on screen for entire 3 minutes.

### Server version

This server is running Paper version 1.21.1-132-ver/1.21.1@b48403b (2024-11-21T10:14:27Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT

### ItemsAdder Version

[16:49:06 INFO]: ItemsAdder version 4.0.6
[16:49:06 INFO]: Customized Minecraft without client mods!
[16:49:06 INFO]: Website: devs.beer
[16:49:06 INFO]: Author: LoneDev

### ProtocolLib Version

[16:49:39 INFO]: ProtocolLib version 5.3.0
[16:49:39 INFO]: Provides read/write access to the Minecraft protocol.
[16:49:39 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[16:50:13 INFO]: LoneLibs version 1.0.63
[16:50:13 INFO]: Collection of libs used by my plugins
[16:50:13 INFO]: Authors: LoneDev and others

### Full Server Log

https://mclo.gs/EwG1kth

### Problematic items yml configuration file (optional)

```yaml
fishcodex_chest:
    display_name: Black Chest
    resource:
      material: CHEST
      generate: false
      model_path: item/black_chest
    behaviours:
      furniture:
        gravity: true
        fixed_rotation: true
        small_hitbox: true
        solid: true
    events_settings: #1200 ########### <-- EXAMPLE 60 seconds   
      cooldown:
        indicator: TITLE 
        ticks: 100       
    events:
      placed_furniture:
        interact:
          execute_commands:
            first_cmd:
              as_console: false
              command: 'fish codex'
```
