### ISSUE TITLE
Move `specific_properties.book` to `book`

### ISSUE THREAD

**Issue by LoneDev6** [LoneDev6/ItemsAdder#4370]
Similar to 
- #4369

This is the NBT of a book:
```
{
  "components": {
    "minecraft:written_book_content": {
      "author": "Author",
      "generation": 1,
      "pages": [
        {
          "raw": "\"test page 1\""
        }
      ],
      "resolved": "1b",
      "title": {
        "raw": "Title"
      }
    }
  },
  "count": 1,
  "id": "minecraft:written_book"
}
```

So I makes sense to move the `specific_properties` to the root of the item, as it's a vanilla attribute.

```yml
  example:
    display_name: example
    book:
      author: ItemsAdder
      generation: ORIGINAL
      pages:
        - page1
        - page2
```

Instead of 
```yml
  example:
    display_name: example
    specific_properties:
      book:
        author: ItemsAdder
        generation: ORIGINAL
        pages:
          - page1
          - page2
```
