### ISSUE TITLE
[BUG] Exception when executing /iazip

### ISSUE THREAD

**Issue by Andre601** [LoneDev6/ItemsAdder#441]
**Describe the bug**
When using `/iazip` an exception is thrown in console. The resourcepack is still compressed an applied tho.

Log from when using `/iazip`: https://paste.helpch.at/aritahanif.md

**To Reproduce**
1. Run /iazip?

**Expected behavior**
No error

**Screenshots**

**Info (please complete the following information):**
 - Server version: PaperMC 1.16.3
 - Client version: Vanilla Minecraft 1.16.3
 - Plugin version: 2.1.10

**Additional context**
Possible related issue:
When destroying blocks using the diamond hammers are gravel/sand floating in midair instead of falling down.

![2020-10-21_22 28 12](https://user-images.githubusercontent.com/11576465/96779509-bda74e00-13ec-11eb-8d56-42f0a9e29374.png)

**Comment by Andre601** [comment]
One thing to add to this is, that when you mine a 3x3 area that contains gravel/sand, that the blocks are destroyed but not droping themself.

**Comment by LoneDev6** [comment]
Are you sure it's related to /iazip?
I think it's just a coincidence.
Anyway I will catch this error and ignore it: seems that a water flow or a break event near a custom block is triggered but the placed custom block was previously removed from config files, so IA doesn't know about this block anymore.





> 
> 
> One thing to add to this is, that when you mine a 3x3 area that contains gravel/sand, that the blocks are destroyed but not droping themself.

check if you set it like this:
```yml
    events:
      block_break:
        multiple_break:
          keep_ores: true
          drop_all_blocks:
            enabled: true
            need_silk_touch: false
          size: 3
```


Comment on this issue if you still need help
