### ISSUE TITLE
Internal Exception: Failed to decode packet 'clientbound/minecraft:level_particles'

### ISSUE THREAD

**Issue by zalan-toth** [LoneDev6/ItemsAdder#4503]
### Discord Username (optional)

enyzat

### What happened?

This issue is related to ItemsAdderBlocksInjector.
I believe I discovered a non critical bug that can cause clients to loose connection from the server when they fall down to an itemsadder block that is generated by a world generator (in this case Iris) using Block Injection. The fall from larger heights would normally result in particles when the user lands on a block, but in this case if the player lands on such generated-injected itemsadder block, it will trigger an internal exception (Failed to decode packet 'clientbound/minecraft:level_particles'. I'd appriciate it if you could check what can be solved on your side. 

### Steps to reproduce the issue

1. Generate a world with custom ores using Iris World Generator with block injection
2. Fall down to a generated-injected itemsadder block from a larger height to trigger particle creation on the block
3. Internal Exception on the client side

### Server version

[23:02:08 INFO]: Checking version, please wait...
[23:02:08 INFO]: This server is running Paper version 1.21.4-207-main@1a7288a (2025-03-09T18:15:59Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)
You are running the latest version

### ItemsAdder Version

[23:02:36 INFO]: ItemsAdder version 4.0.9
[23:02:36 INFO]: Customized Minecraft without client mods!
[23:02:36 INFO]: Website: devs.beer
[23:02:36 INFO]: Author: LoneDev

### ProtocolLib Version

[23:02:52 INFO]: ProtocolLib version 5.4.0-SNAPSHOT-741
[23:02:52 INFO]: Provides read/write access to the Minecraft protocol.
[23:02:52 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

[23:03:03 INFO]: LoneLibs version 1.0.65
[23:03:03 INFO]: Collection of libs used by my plugins
[23:03:03 INFO]: Authors: LoneDev and others

### Full Server Log

[https://mclo.gs/GRVInEN](https://mclo.gs/GRVInEN)

### Error (optional)

```shell
Clientside error: Internal Exception: Failed to decode packet 'clientbound/minecraft:level_particles'
```

### Problematic items yml configuration file (optional)

```yaml
The example block that was generated with injection into a simple Iris World:
  solarstone_aluminium_ore:
    display_name: Solarstone Aluminium Ore
    permission: solarstone
    resource:
      generate: true
      material: PAPER
      texture: block/ore/aluminium_ore/solarstone_aluminium_ore.png
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          break_particles: ITEM
```

### Other files, you can drag and drop them here to upload. (optional)

All Plugins on the bare minimum server to reproduce the issue:
**Iris World Generator** v3.6.3 (Newest)
**ItemsAdder** 4.0.9 (Newest)
**ItemsAdder-Block-Injector** 0.0.16 (Newest)
**LoneLibs** 1.0.65 (Newest)
**ViaVersion-5.2.1** (Newest)
**ProtocolLib** 741 (Newest)
**MyWorlds** 1.21.4-v1-323 (Snapshot for 1.21.4)
**BKCommonLib** 1.21.4-v1-1835 (Snapshot for 1.21.4)

Everything else works as intended, so there are no other anomalies surrounding this issue.

### Screenshots/Videos (you can drag and drop files or paste links)

![Image](https://github.com/user-attachments/assets/173ff685-499c-43d6-8c15-55c0c480fae4)

Video:
[https://youtu.be/33OypP0PlAI](https://youtu.be/33OypP0PlAI)
