### ISSUE TITLE
Allow multiple items as a possible Ingredient in the grafting table

### ISSUE THREAD

**Issue by Andre601** [LoneDev6/ItemsAdder#4540]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [x] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

andre601

### Describe the solution you'd like

A way to define multiple items as a possible ingredient for a recipe, allowing a player to use any of them to craft.

As an example, assume we want to make a wooden hammer and allow any wood type for it to be crafted. With the proposed feature could we do this:

```yaml
info:
  namespace: hammertime
recipes:
  crafting_table:
    pattern:
      - 'XWX'
      - 'WSX'
      - 'XXS'
    pattern_2:
      - 'XWX'
      - 'XSW'
      - 'SXX'
    ingredients:
      W:
        - OAK_PLANKS
        - SPRUCE_PLANKS
        - BIRCH_PLANKS
        - JUNGLE_PLANKS
        - ...
      S: STICK
    result:
      item: hammertime:wooden_hammer
```
...or if technically possible, maybe also allow using item tags as ingredients for easier setup:

```yaml
info:
  namespace: hammertime
recipes:
  crafting_table:
    pattern:
      - 'XWX'
      - 'WSX'
      - 'XXS'
    pattern_2:
      - 'XWX'
      - 'XSW'
      - 'SXX'
    ingredients:
      W: '#minecraft:planks' # Would allow any item with the tag minecraft:planks (any wood type)
      S: STICK
    result:
      item: hammertime:wooden_hammer
```

### Is your feature request related to a problem?

If you want to allow multiple item types to be used to craft the same item are you required to repeat the same recipe `<patterns> * <allowed ingredient variants>` times, making it a tedious job, especially if you need to update `n` patterns if the recipe gets changed.

### Describe alternatives you've considered

The above mentioned of having to create the same recipe `<variants>` times.
