### ISSUE TITLE
Shift click crafting result not working

### ISSUE THREAD

**Issue by LoneDev6** [LoneDev6/ItemsAdder#4649]
https://github.com/user-attachments/assets/f048d1ce-0b4c-412c-9cd0-fbed6b60fe55

```yml
ruby_boots:
    display_name: "Bottes en Rubis"
    item_flags:
      - HIDE_ATTRIBUTES
    resource:
      generate: true
      textures:
      - ruby_boots.png
      - ruby_boots.png
    durability:
      max_custom_durability: 1029
    specific_properties:
      armor:
        slot: FEET
        custom_armor: ruby
    attribute_modifiers:
      feet:
        armor: 6
        armorToughness: 5

ruby_boots:
      enabled: true
      pattern:
      - AXA
      - AXA
      - XXX
      ingredients:
        A: minerals_pack:ruby
      result:
        item: tools_armors_pack:ruby_boots
        amount: 1  
```

https://discord.com/channels/533407895010803753/1367857283278831716/1368941233392844820
