### ISSUE TITLE
Refactoring of the custom armors shaders configuration

### ISSUE THREAD

**Issue by LoneDev6** [LoneDev6/ItemsAdder#4674]
From
```yml
    generate-custom-armors-textures:
      vanilla: true
      optifine_nbt: false
      overwrite_leather_armor_layers_textures: true
      1_21_5_plus_armors_shaders: true
```

To
```yml
    custom_armors_shaders_legacy:
      vanilla:
        overwrite_leather_layers: true
        generate_textures: true
        generate_shader:
          1_21_4_lower: true
          1_21_5_plus: false
      optifine:
        generate_cit:
          1_20_4_lower: false
```
