### ISSUE TITLE
Loots - execute commands

### ISSUE THREAD

**Issue by LoneDev6** [LoneDev6/ItemsAdder#4752]
Implement a way to execute commands in loots.

Example: spawn a custom mob when a vanilla mob dies.

```yml
loots:
  mobs:
    zombie:
      type: ZOMBIE
      commands:
        my_commands_list_1:
          chance: 100
          my_command_1:
            command: iaentity summon vanillaex:crawler_zombie {world} {target-x} {target-y} {target-z} {target-yaw} {target-pitch}
```

Example: spawn a custom mob when a block is broken

```yml
loots:
  blocks:
    redstone_ore:
      type: REDSTONE_ORE
      commands:
        my_list_1:
          chance: 100
          my_command_1:
            command: iaentity summon vanillaex:redstone_bug {world} {target-x} {target-y} {target-z} {target-inverse-yaw} {target-pitch}
```
