### ISSUE TITLE
place_furniture does not work

### ISSUE THREAD

**Issue by EspartaProJunior** [LoneDev6/ItemsAdder#4794]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [x] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [x] I searched the `#itemsadder-forum` channel on Discord for similar issues.
- [x] I tested that this issue persists on a **bare-minimum Server** as described in [#4187](https://github.com/PluginBugs/Issues-ItemsAdder/issues/4187).

### Discord Username (optional)

master_masaki

### What happened?

I get this error and I don't understand as it is exactly as the wiki says
[10:04:17] [Craft Scheduler Thread - 114 - ItemsAdder/ERROR]: [ItemsAdder] Invalid furniture 'elitefantasy:blue_giant_mushroom' for 'place_furniture' action of item 'elitefantasy:blue_giant_mushroom_item'. File: /contents/elitefantasy/configs/dig_and_decorate/dig_and_decorate_vol2.yml

wiki part: https://itemsadder.devs.beer/plugin-usage/adding-content/furniture/furniture-2d-icon

### Steps to reproduce the issue

just the config dont work, still doesn't work, so I put furniture: elitefantasy:blue_giant_mushroom or furniture: blue_giant_mushroom

### Server version

Paper 1.21.3-82-ver/1.21.3@5a60ffb

### ItemsAdder Version

ItemsAdder (4.0.11)

### ProtocolLib Version

ProtocolLib (5.4.0-SNAPSHOT-748)

### Full Server Log

https://mclo.gs/5Gjk3Qv

### Error (optional)

```shell
<html>
<body>
<!--StartFragment-->
[10:04:17] [Craft Scheduler Thread - 114 - ItemsAdder/ERROR]: [ItemsAdder] Invalid furniture 'elitefantasy:blue_giant_mushroom' for 'place_furniture' action of item 'elitefantasy:blue_giant_mushroom_item'. File: /contents/elitefantasy/configs/dig_and_decorate/dig_and_decorate_vol2.yml
--
849 | [10:04:17] [Craft Scheduler Thread - 114 - ItemsAdder/ERROR]: [ItemsAdder] Invalid furniture 'elitefantasy:blue_giant_mushroom' for 'place_furniture' action of item 'elitefantasy:blue_giant_mushroom_item'. File: /contents/elitefantasy/configs/dig_and_decorate/dig_and_decorate_vol2.yml
850 | [10:04:17] [Craft Scheduler Thread - 114 - ItemsAdder/ERROR]: [ItemsAdder] Invalid furniture 'elitefantasy:green_giant_mushroom' for 'place_furniture' action of item 'elitefantasy:green_giant_mushroom_item'. File: /contents/elitefantasy/configs/dig_and_decorate/dig_and_decorate_vol2.yml
851 | [10:04:17] [Craft Scheduler Thread - 114 - ItemsAdder/ERROR]: [ItemsAdder] Invalid furniture 'elitefantasy:pickaxe_in_wall' for 'place_furniture' action of item 'elitefantasy:pickaxe_in_wall_item'. File: /contents/elitefantasy/configs/dig_and_decorate/dig_and_decorate_vol2.yml
852 | [10:04:17] [Craft Scheduler Thread - 114 - ItemsAdder/ERROR]: [ItemsAdder] Invalid furniture 'elitefantasy:reinforced_torch' for 'place_furniture' action of item 'elitefantasy:reinforced_torch_item'. File: /contents/elitefantasy/configs/dig_and_decorate/dig_and_decorate_vol2.yml
853 | [10:04:17] [Craft Scheduler Thread - 114 - ItemsAdder/ERROR]: [ItemsAdder] Invalid furniture 'elitefantasy:reinforced_torch_wall' for 'place_furniture' action of item 'elitefantasy:reinforced_torch_wall_item'. File: /contents/elitefantasy/configs/dig_and_decorate/dig_and_decorate_vol2.yml
854 | [10:04:17] [Craft Scheduler Thread - 114 - ItemsAdder/ERROR]: [ItemsAdder] Invalid furniture 'elitefantasy:sword_in_wall' for 'place_furniture' action of item 'elitefantasy:sword_in_wall_item'. File: /contents/elitefantasy/configs/dig_and_decorate/dig_and_decorate_vol2.yml

<!--EndFragment-->
</body>
</html>
```

### Problematic items yml configuration file (optional)

```yaml
items:
  blue_giant_mushroom_item:
    display_name: "Blue Giant Mushroom"
    resource:
      material: PAPER
      generate: true
      model_id: 1329
      textures:
      - custom/items/blue_giant_mushroom_item
    events:
      interact:
        right:
          place_furniture:
            furniture: elitefantasy:blue_giant_mushroom
            decrement_amount: true
        right_shift:
          place_furniture:
            furniture: elitefantasy:blue_giant_mushroom
            decrement_amount: true
  blue_giant_mushroom:
    display_name: "Blue Giant Mushroom"
    resource:
      material: PAPER
      generate: false
      model_path: custom/items/blue_giant_mushroom
      model_id: 1330
    behaviours:
      furniture:
        solid: true
        entity: item_frame
        cancel_drop: true
        placeable_on:
          floor: true
          ceiling: false
          walls: false
    events:
      placed_itemframe:
        break:
          drop_item:
            item: blue_giant_mushroom_item
```
