### ISSUE TITLE
HUD suggestions

### ISSUE THREAD

**Issue by PSYCHEER** [LoneDev6/ItemsAdder#4795]
### Terms

- [x] I'm using the very latest version of ItemsAdder and its dependencies.
- [x] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same suggestion was already reported.
- [x] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if the feature is already implemented.
- [x] I already searched on the **Discord** server to know if anyone already has a solution for this or if the feature was already suggested.

### Discord tag (optional)

PSYCHEER

### Describe the solution you'd like

Hey there! I'm in last time playing with HUDs in a massive size and I've found that HUD (e.g. thirst) can't have option to be decreased based on player movement, jump, attacks, swimming etc.

I will want to see these options in ItemsAdder as having HUD which in-/de-creases only with time or food value change is a bit underrating of this precious system.

In future I'll want to do a stamina thingy for my server too, without those I'll have to search for third party plugins which can somehow do it trough commands or wait for global scripts in ItemsAdder.

Some HIDE option to "must not specify" images. I have to use images like here (it's one png file which is fully transparent) as I'm using another HUD plugin which does a bit better job with fonts etc as it supports not only vanilla-like things

```yaml
info:
  namespace: hudsystem
huds:
  thirst_bar:
    enabled: true
    show:
      auto: true
      creative: true
      underwater: true
      riding: true
    type: STATUS
    x_position_pixels: 5
    direction: LEFT
    value:
      player_stat_name: thirst
      start: 20
      min: 0
      max: 20
      triggers:
        decrement:
          #region What I want to see
          player_walks: # or player_walks_sprint for sprinting
            multiplier: 1 # Decrement of 1 for every 1 block player went) e.g. multiplier 2 will be decrement of 2 for every block etc (default can be 0)
            chance: 100 # Percentual chance if this decrement will be successful
          player_jumps:
            multiplier: 1 # Decrement of 1 for every jump
            chance: 100
          player_swims: # or player_swims_fast for "sprinting" while swimming
            multiplier: 1
            chance: 100
          player_attack: # can be in three parts, `player_melee_attack`, `player_ranged_attack` and `player_attack` (player_attack will combine both of)
            multiplier: 1 # Decrement of 1 per every heart he damaged its victim
            chance: 100
          player_sneaks: # Good for some stealth indicator
            multiplier: 1 (Decrement of 1 per every block player went trough while sneaking
            chance: 100

          # multiplier have to be float
          # I will want same of those in increment as well
          #endregion 
          generic_over_time_30_minutes_inside:
            min_sky_light: 0
            max_sky_light: 13
            every_ticks: 36000
            amount: 1
          generic_over_time_30_minutes_outside:
            min_sky_light: 14
            max_sky_light: 15
            every_ticks: 36000
            amount: 1
          biome_over_time_desert_30_minutes_inside:
            min_sky_light: 0
            max_sky_light: 6
            biome: DESERT
            every_ticks: 36000
            amount: 2
          biome_over_time_desert_30_minutes_outside:
            min_sky_light: 7
            max_sky_light: 15
            biome: DESERT
            every_ticks: 36000
            amount: 2
        increment:
          player_respawn:
            amount: 20
        on_min_value:
          damage_player:
            every_ticks: 100
            damage: 1
          
          potion_effect:
            every_ticks: 100
            type: SLOWNESS
            amplifier: 1
            duration: 100
            
    images:
      hide: boolean # (true|false) for no need to set images when on `true`
      positive: mypack:thirst_bar_positive
      negative: mypack:thirst_bar_positive
      half: mypack:thirst_bar_positive
```

### Is your feature request related to a problem?

Future-proof

### Describe alternatives you've considered

Denizen (No playerstat implementation yet)
Skript
