### ISSUE TITLE
Custom entities - set entity goals

### ISSUE THREAD

**Issue by LoneDev6** [LoneDev6/ItemsAdder#4799]
Allow setting entity goals to make the custom entities behaviour more dynamic.
In the future I will add support to more goals, for now these are more than enough to customize the experience.

Note:
`clear_all` is used to clear every base goal in the vanilla entity.
`replace_vanilla` is used to clear any base goal of the same type in the vanilla entity.

Some examples:
```yml
goals:
  clear_all: true

  look_at_entity:
    enabled: true
    replace_vanilla: true
    priority: 10
    entity: ZOMBIE
    chance: 80
    look_forward: false
    selector:
      min_health: 10.0
      max_health: 20.0
      equipment:
        match_all: false
        helmet: DIAMOND_HELMET
        main_hand: minecraft:diamond_sword

  random_look_around:
    enabled: true
    replace_vanilla: true
    priority: 5

  random_wander_around:
    enabled: true
    replace_vanilla: true
    priority: 6
    speed_modifier: 1.2
    interval: 10
    check_no_action_time: true

  attack_near:
    enabled: true
    replace_vanilla: true
    priority: 7
    entity: myplugin:entity_1
    must_be_angry_at: true
    interval: 20
    check_visibility: true
    check_can_navigate: false
    selector:
      min_health: 5
      equipment:
        helmet: LEATHER_HELMET
        main_hand: minecraft:wooden_sword

  melee_attack:
    enabled: true
    replace_vanilla: true
    priority: 4
    speed_modifier: 1.0
    pause_when_idle: true

  ranged_bow_attack:
    enabled: true
    replace_vanilla: true
    priority: 3
    speed_modifier: 1.1
    attack_interval_min: 30
    attack_radius: 16

  avoid_entity:
    enabled: true
    replace_vanilla: true
    priority: 2
    entity: SKELETON
    selector:
      max_health: 10
      equipment:
        match_all: true
        chestplate: CHAINMAIL_CHESTPLATE

  hurt_by_target:
    enabled: true
    replace_vanilla: true
    priority: 8
    ignore_damage_from_entities:
      - ZOMBIE
      - SPIDER
    alert_others_types:
      - VILLAGER
      - IRON_GOLEM

  avoid_sun:
    enabled: true
    replace_vanilla: true
    priority: 9

  float:
    enabled: true
    replace_vanilla: true
    priority: 1

  move_to_block:
    enabled: true
    replace_vanilla: true
    priority: 6
    speed_modifier: 1.0
    search_range: 16
    blocks:
      - minecraft:stone
      - minecraft:cherry_trapdoor[open=true]
      - myplugin:custom_block

  open_door:
    enabled: true
    replace_vanilla: true
    priority: 5
    close: true

  break_door:
    enabled: true
    replace_vanilla: true
    priority: 5

  eat_block:
    enabled: true
    replace_vanilla: true
    priority: 7
    blocks:
      - STONE
      - minecraft:grass_block
      - myplugin:custom_food_block


```
