### ISSUE TITLE
Custom structure to spawn custom entities (like vanilla `WITHER`)

### ISSUE THREAD

**Issue by LoneDev6** [LoneDev6/ItemsAdder#4818]
Draft:

```yml
custom_entity_structure:
  enable:
  pattern:
    - 'XAX'
    - 'XAX'
    - 'AXA'
  blocks:
    - A: IRON_BLOCK
```
