### ISSUE TITLE
[Suggestion] Customizable Custom Tree shapes/sizes

### ISSUE THREAD

**Issue by ArgonGaming** [LoneDev6/ItemsAdder#521]
**Is your feature request related to a problem? Please describe.**
The only problem with this amazing tree update utilizing Chorus fruit's transparency, is that all the trees are shaped the same. I believe this makes it boring in essence to have many different looking trees the same size and shape.

**Describe the solution you'd like**
The solution would be to somehow implement a method to have a variation of sizes (a vanilla default), and perhaps on top of that, the option to create our own shapes AND sizes with a variation feature. Perhaps with a schematic file method like other plugins do when they deal with custom structures in world generation. Spike has recommended this before as well, but Saplings would be a very nice touch to this WITH the variation. This variation would trigger for both its spawn into the world, and if the saplings are added, for the dappling growth as well.

**Additional context**
![image](https://user-images.githubusercontent.com/30943826/99632687-9f446a80-2a0b-11eb-935b-dd6ae0102fda.png)

**Comment by LoneDev6** [comment]
I don't think I will work on this as it'll make the generation very slow.
Currently I generate trees using internal Minecraft code which is very fast. Schematics are not, sorry!


You can change the tree type tho.
![image](https://user-images.githubusercontent.com/27242001/100853332-ef99de80-3487-11eb-9881-1fee5825a66b.png)
![Uploading image.png…]()

```yml
info:
  namespace: newtrees
trees_populators:
  orange_tree:
    worlds:
    - world
    chance: 5.0
    max_height: 100
    min_height: 50
    amount: 3
    iterations: 2
    log: newtrees:orange_tree_log
    leaves: newtrees:orange_tree_leaves
    tree_type: TALL_BIRCH
    biomes:
    - MOUNTAINS
```
