### ISSUE TITLE
[Suggestion] Add an option to disable automatic show all categories

### ISSUE THREAD

**Issue by R-Josef** [LoneDev6/ItemsAdder#522]
**Is your feature request related to a problem? Please describe.**
I have localized the ia_gui.yml file, i found that the latest version will show all categories automatic, but it makes me can not custom category names, i want translate them to chinese.

**Describe the solution you'd like**
Add an option to disable automatic show all categories.
Example:
```yaml
categories:
  show_all_categories: true
  all:
    enabled: true
    icon: "itemsadder:ruby_block"
    name: display-category-all
    show_all_items: true
    hide_items:
      - "......"
```

**Describe alternatives you've considered**
Add all of default category names to language file.

**Comment by LoneDev6** [comment]
Hello! I don't understand what you mean, they are already translated to chinese since some updates ago:

```yaml
info:
  namespace: itemsadder_stuff
  dictionary-lang: "zh_cn"
dictionary:
  display-category-all: 全部
  display-category-armors: 护甲
  display-category-swords: 武器
  display-category-pickaxes: 镐子
  display-category-axes: 斧子
  display-category-hoes: 锄头
  display-category-shovels: 铲子
  display-category-fishing_rods: 钓鱼竿
  display-category-shears: 剪刀
  display-category-weapons: 枪械
  display-category-shields: 盾牌
  display-category-bows: 弓
  display-category-eatables: 食物
  display-category-drinks: 饮料
  display-category-vegetables: 蔬菜与水果
  display-category-seeds: 种子
  display-category-fishes: 鱼
  display-category-potions: 药剂
  display-category-furnitures: 家具
  display-category-paintings: 画
  display-category-chairs: 椅子
  display-category-hats: 帽子
  display-category-wearables: 饰品
  display-category-machines: 机器
  display-category-blocks: 方块
  display-category-ores: 矿石原矿
  display-category-minerals: 矿物
  display-category-instruments: 乐器
  display-category-various: 物品与原料
  display-category-alchemy: 魔力物品
  display-category-musicdiscs: 唱片
  display-category-throwables: 投掷物
  display-category-books: 书籍
  display-category-vehicles: 载具
  display-category-icons: 图标
  display-category-generic_items: 通用物
  display-category-halloween: 万圣节物品
  display-category-christmas: 圣诞物品
  display-category-special: 特殊物品
  display-category-realcraft: 饮水
```
