### ISSUE TITLE
[SUPPORT REQUEST] Configurazione degli Zainetti (suoni personalizzati)

### ISSUE THREAD

**Issue by Fargus5** [LoneDev6/ItemsAdder#533]
Ciao Matté, senti ho provato a iniziare a caricare i suoni delle zip degli zainetti.
Però non ci sono riuscito. Secondo te è scritto bene cosi il file config?

```
items_lang: en_us
pickup_items_into_backpacks: true
max_bp_in_inventory: 999
gui_rows: 6
disable_put_in_enderchest: true
disable_put_in_shulkerboxes: true
disable_drop_backpacks: false
add_recipes_in_recipebook_on_join: true
use_actionbar_for_messages: false
debug:
  backpacks-loa-log: true
  backpacks-load-log: true
disable_open_with_off_hand: false
open_backpacks_interval_ms: 700
backpacks-sounds: true
personal_backpacks:
  sounds:
    open:
      name: music:backpack_zip1
      volume: 1
      pitch: 0.5
    close:
      name: music:backpack_zip2
      volume: 1
      pitch: 0.5
    click:
      name: ENTITY_ITEM_FRAME_ADD_ITEM
```

Non so se funziona...

**Comment by Fargus5** [comment]
Inoltre il reload degli zainetti non funziona


https://log.mtxserv.com/Q1oaarq

**Comment by Fargus5** [comment]
Allora, dopo svariati tentativi... mi sono reso conto di una cosa...

```
backpacks-sounds: true
personal_backpacks:
   sounds:
      open:
        name: BLOCK_CHEST_OPEN
        volume: 1
        pitch: 1
      close:
        name: BLOCK_CHEST_CLOSE
        volume: 1
        pitch: 1
      auto_pickup:
        name: ENTITY_ITEM_PICKUP
      click:
        name: ENTITY_ITEM_FRAME_ADD_ITEM
```` 

Non importa come cambiamo questi valori...
anche inserendo i suoni di minecraft, restano sempre invariati.
Quindi... c'è sicuramente un problema nei codici che non rimanda a questa selezione.

**Comment by Fargus5** [comment]
Ciao Matteo,
Ti ringrazio della risposta, ma non capisco per quale motivo dovrebbe essere music PUNTO invece di DUEPUNTI, visto e considerato che in ogni sezione di ItemsAdder e anche come me ne hai dato dimostrazione tu inserendo il suo angelico, dopo il namespace bisogna mettere i DUEPUNTI.

Ad ogni modo il problema non si presentava solo con i custom sounds, anche inserendo normali suoni di minecraft il suono riprodotto rimaneva invariato. Come se la modifica non venisse presa in conto.
Ad ogni modo ti mostro per filo e per segno dove ho posizionato i file .ogg

![image](https://user-images.githubusercontent.com/20026629/101196910-ac936300-3661-11eb-9da7-f631c9d0dfdb.png)

![image](https://user-images.githubusercontent.com/20026629/101196948-bcab4280-3661-11eb-9173-3b50751dac92.png)

Facendo il test con /playsound questi due suoni si sentono benissimo.

Inoltre lasciando rigenerare il file config si nota immediatamente che le novità che hai aggiunto non vengono caricate:

![image](https://user-images.githubusercontent.com/20026629/101197184-101d9080-3662-11eb-8765-78ad60a5f67b.png)

Non viene mostrato questo:
      auto_pickup:
       name:...

Che ho provveduto ad aggiungere manualmente

Ora provo a fare un riavvio del server inserendo i due aggiornamenti che hai rilasciato una trentina di minuti fa e ti faccio sapere:

provo questa configurazione qui:
![image](https://user-images.githubusercontent.com/20026629/101197987-16f8d300-3663-11eb-8aa9-c0c860afe713.png)

Dopo un riavvio, non è cambiato nulla... i suoni restano quelli di default che hai messo tu.

Anche il suono angelico non si sente. Io sento quello di defautl che avevi messo tu.

**Comment by LoneDev6** [comment]
Ho solo ipotizzato non sapendo com'era strutturato.

Comunque quindi usando `/ebp` non senti il suono modificato?
Il file config.yml contiene i suoni per il personal backpack accessibile con /ebp, mentre il file backpacks.yml contiene le configurazioni di ogni singolo backpack fisico in cui puoi decidere suoni diversi per ciascuno

**Comment by Fargus5** [comment]
ah si facendo il comando /ebp funziona....
eh ma Matteo non l'avrei mai immaginato da solo che potevo personalizzarlo in ogni cosino.

io ho il file cosi per i singoli:

```
backpacks:
  grocery_bag:
    display_name: '&fGrocery Bag'
    item:
      type: ITEMSADDER_ITEM
      name: "itemsadder:plastic_bag"
    size: 1
    craft_recipe:
      pattern:
        - XXX
        - LCL
        - XLX
      ingredients:
        L: LEATHER
        C: CHEST
```

in che modo devo inserire il codice, cosi?

```
backpacks:
  grocery_bag:
    display_name: '&fGrocery Bag'
    item:
      type: ITEMSADDER_ITEM
      name: "itemsadder:plastic_bag"
    size: 1
    craft_recipe:
      pattern:
        - XXX
        - LCL
        - XLX
      ingredients:
        L: LEATHER
        C: CHEST
    sounds:
      open:
        name: music:backpack_zip1
        volume: 1
        pitch: 0.5
      close:
        name: music:backpack_zip2
        volume: 1
        pitch: 0.5
      put_item:
        name: ENTITY_ITEM_FRAME_ADD_ITEM
        volume: 1
        pitch: 0.5
      click:
        name: ENTITY_ITEM_FRAME_ADD_ITEM    
```

**Comment by LoneDev6** [comment]
Eppure ti avevo mandato il file con l'esempio dove era specificato appunto per evitare questa situazione:
```yml
backpacks:
  example_1:
    enabled: false
    display_name: '&fexample'
    can_auto_pickup: false
    item:
      type: HEAD
      texture: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMmEzYjM0ODYyYjlhZmI2M2NmOGQ1Nzc5OTY2ZDNmYmE3MGFmODJiMDRlODNmM2VhZjY0NDlhZWJhIn19fQ=='
      lore:
        - "&6[ &ePortable Backpack &6]"
        - "&fYou can store any item."
    size: 2
    blacklist:
      - BARRIER
      - BEDROCK
    craft_recipe:
      amount: 4
      pattern:
        - XOX
        - XEX
        - XOX
      ingredients:
        O: OBSIDIAN
        E: ENDER_CHEST
    sounds:
      open:
        name: ENTITY_ENDER_DRAGON_FLAP
        volume: 1
        pitch: 0.5
      close:
        name: ENTITY_ENDER_DRAGON_FLAP
        volume: 1
        pitch: 0.5
      auto_pickup:
        name: ENTITY_ITEM_PICKUP
      click:
        name: ENTITY_ITEM_FRAME_ADD_ITEM
```
