### ISSUE TITLE
[BUG] New action animated title.

### ISSUE THREAD

**Issue by ValouProjet** [LoneDev6/ItemsAdder#536]
**Describe the bug**
I have a problem with one of the new functionnalities : play animated title.
There is my file :

mineraicronium:
    display_name: '&rMinerai de cronium'
    permission: bloc
    events:
      placed_block.break:
        play_totem_animation:
          animatedtitles:bruh

But it doesn't play the animation... any ideas :/ ?
I also tried what u wrote on the wiki, but i'm sure it's not the right syntax and something is wrong, u wrote that :
play_totem_animation: animatedtitles:bruh.

**Expected behavior**
Play the animated title

**Info (please complete the following information):**
 - Server version: Spigot 1.15.2
 - Client version: Official minecraft client 1.15.2
 - Plugin version: 2.1.20

**Comment by LoneDev6** [comment]
```yml
items:
  mineraicronium:
    display_name: '&rMinerai de cronium'
    permission: mineraicronium
    resource:
      material: IRON_ORE
      generate: true
      textures:
      - item/mineraicronium.png
    specific_properties:
      block:
        placed_model:
          type: REAL
          break_particles: BLOCK
    events:
      placed_block:
        break:
          play_totem_animation: animatedtitles:bruh
```

**Comment by ValouProjet** [comment]
Yes i already tested it and asked help on the discord but it doesn't work, even other members have trouble with it.

**Comment by ValouProjet** [comment]
I think there is something wrong in it (or the syntax is not the good one) you should try it again

**Comment by LoneDev6** [comment]
Just tried and it's working fine

```yml
  ruby_block:
    display_name: display-name-ruby_block
    permission: ruby_block
    resource:
      material: REDSTONE_BLOCK
      generate: true
      textures:
      - block/ruby_block.png
    specific_properties:
      block:
        placed_model:
          type: REAL
          break_particles: BLOCK
        break_tools_whitelist:
        - PICKAXE
        - pickaxe
    events:
      placed_block:
        break:
          play_totem_animation: animatedtitles:bruh
```
