### ISSUE TITLE
[Suggestion] New Crop System

### ISSUE THREAD

**Issue by YoutubeNosios** [LoneDev6/ItemsAdder#554]
**Is your feature request related to a problem? Please describe.**
Create a bush system like experience bushes from tinker's construct.

**Describe the solution you'd like**
When you place a block , after a random amount of time it will change to another block.

**Additional context**
You can do that with bukkit runnables and random tick speed

**Comment by PSYCHEER** [comment]
Suggestions:
Item_display and age tag for custom plants.
As with block tags and item_display is already possible to implement it into the game, it can be based on fern behaviour…
Why fern? To have plant collider/hitbox which is visible but trigger and comes in 2 sizes, so for 1 or 2 block plants will be not needed almost any workaround!

For corn-like plants can be used bamboo or sugar cane.

**Comment by JustinTheBob** [comment]
I cant wait! This is the only feature holding me from switching from Oraxen to itemsadder! + another $20 in your pocket sir when this feature is done! <3

**Comment by iambibi** [comment]
Are you going to add events in the API to detect the breakage of a crop? (or could this be done with the CustomBlockBreakEvent?)

**Comment by LoneDev6** [comment]
Work in progress, example configurations (may change during development):

```yml
crops:
  test_crop:
    id_prefix: "test_crop_stage_"
    hitbox_auto_height_step: 0.1
    max_age: 7
    default_hitbox:
      width: 1.0
      length: 1.0
      height: 0.1
    seed: test_crop_seed2
    avg_seconds_per_stage: 240 # Overrides the global setting in config.yml
    min_light: 9
    view_range: 0.4
    bottom_block: farmland
    place_sound: minecraft:item.crop.plant
    break_sound: minecraft:block.crop.break
    multipliers:
      bonemeal: 0.2
      max_moisture: 0.5
      rain: 0.7
      thunderstorm: -0.5
      snow: -0.7
```

Alternative, to customize hitbox per-stage.

```yml
  test_crop:
    id_prefix: "test_crop_stage_"
    hitbox_height_step: 0.1
    max_age: 7
    hitboxes:
      0:
        height: 0.1
      1:
        height: 0.2
      2:
        height: 0.3
    default_hitbox:
      width: 1.0
      length: 1.0
      height: 0.1
```


Loots

```yml
  test_crop:
    id_prefix: "test_crop_stage_"
    hitbox_height_step: 0.1
    max_age: 7
    hitboxes:
      0:
        height: 0.1
      1:
        height: 0.2
      2:
        height: 0.3
    default_hitbox:
      width: 1.0
      length: 1.0
      height: 0.1
    seed: test_crop_seed
    avg_seconds_per_stage: 240 # Overrides the global setting in config.yml
    min_light: 9
    view_range: 0.4
    # bottom_block: farmland
    place_sound: minecraft:item.crop.plant
    break_sound: minecraft:block.crop.break
    multipliers:
      bonemeal: 0.2
      max_moisture: 0.5
      rain: 0.7
      thunderstorm: -0.5
      snow: -0.7
    break_loots:
      # Drop the loot only when age range is 1-2 (inclusive)
      test_crop:
        id: test_crop
        age_range:
          min: 1
          max: 2
        items:
          change_me:
            item: EMERALD
            min_amount: 1
            max_amount: 1
            chance: 99.9
            ignore_fortune: false
    interact_loots:
      # Drop the loot only when age is 3
      test_crop_1:
        id: test_crop
        decrease_age: 3
        age: 3
        commands:
          my_group_1:
            chance: 100
            my_command_1:
              command: xxx
        exp:
          exp1:
            min_amount: 1
            max_amount: 1
            chance: 99.9
        items:
          change_me:
            item: DIAMOND
            min_amount: 1
            max_amount: 1
            chance: 99.9
            ignore_fortune: false
```
