### ISSUE TITLE
[BUG] Option "drop_on_silktouch"

### ISSUE THREAD

**Issue by ValouProjet** [LoneDev6/ItemsAdder#562]
**Describe the bug**
In the V.1 of IA, there was an option to remove the enchantment silktouch on ores.
This option doesn't work anymore in the V.2 of ItemsAdder.

**To Reproduce**
It's just not working.

**Expected behavior**
With the option drop_on_silktouch: true, i was able to make an experience ore (look at the photo) (fairly well known on survival / faction / rp servers)
that is working like this with I.A : You create an ore that doesn't drop anything. You just create an event like this :

events:
      placed_block.break:
        drop_exp:
          chance: 100
          min_amount: 30
          max_amount: 60

![2020-12-18_18 09 22](https://user-images.githubusercontent.com/57060565/102641430-5859aa00-415c-11eb-9c04-838a8aa22da6.png)

          
So, when you break the block, you win an amount of experience. BUT without the option "drop_on_silktouch: false", this is a bug abuse because players can just destroy the block with silktouch, win xp and do it again and again cause they receive the block again.

This is only an EXAMPLE of why "drop_on_silktouch" was a good option and you should put it back.

**Info (please complete the following information):**
 - Server version: (spigot 1.15.2)
 - Client version: Official minecraft client 1.15.2
 - Plugin version: 2.1.20

**Additional context**
I don't even know if you remove this option or if it's a bug but it's not on the new wiki + i tested it and it's not working.
It was a rlly good option, hope u'll put it back.

Have a nice day LoneDev ;) !!

**Comment by LoneDev6** [comment]
I'm sorry for the delay, in the new update I fixed it this way, to avoid other duplication exploit:
"placed_block break" event won't be called if the player breaks the block with a silk touch enchanted item.

So your exp ore should be configured like this in the new update:
```yml
  exp_ore:
    display_name: display-name-exp_ore
    permission: exp_ore
    resource:
      material: STONE
      generate: true
      textures:
      - block/exp_ore.png
    specific_properties:
      block:
        hardness: 3
        cancel_drop: true
        placed_model:
          type: REAL
          break_particles: BLOCK
        break_tools_whitelist:
        - PICKAXE
        - pickaxe
    events:
      placed_block:
        break:
          drop_exp:
            chance: 100
            min_amount: 30
            max_amount: 60
```
