### ISSUE TITLE
[Suggestion] Option to remove the enchantment fortune.

### ISSUE THREAD

**Issue by ValouProjet** [LoneDev6/ItemsAdder#563]
**Is your feature request related to a problem? Please describe.**
The suggestion is simple.
On my server i have an ore and i don't want my players to get more than 1 mineral from this ore, EVEN WITH the enchantment fortune on the pickaxes.

**Describe the solution you'd like**
I would like to add an option to remove the enchantment fortune on ores (or just the fact that you only receive a defined number of minerals (1 in my case) when u mine an ore, Fortune OR NOT).

Thanks for your work LoneDev :) !!

**Comment by LoneDev6** [comment]
Thanks, I added this in the new update.
Set **ignore_fortune: true** in your loot https://itemsadder.plugin.ga/plugin-usage/adding-content/advanced/loots#ignore-fortune-enchant
```yml
loots:
  blocks:
    ruby_ore:
      type: itemsadder:ruby_ore
      items:
        ruby:
          item: itemsadder:ruby
          min_amount: 1
          max_amount: 2
          chance: 100
          ignore_fortune: true
```
