### ISSUE TITLE
[Suggestion] Option to Disable ActionBar Message

### ISSUE THREAD

**Issue by Xuwznln** [LoneDev6/ItemsAdder#570]
**Is your feature request related to a problem? Please describe.**
I use an addon called betterhud. This shows thirsty and health info with bossbar instead of actionbar. So if I want to enable built-in thirsty function, action bar will still show something invisible and sometimes show a word "null". I only want thirsty function but dont want to show the action-bar  message.

**Describe the solution you'd like**
Provide an option like:
```
  thirst:
    enabled: true
    show:
      **disable: true**
      auto: false
      creative: false    
      underwater: false
      riding: false
```
**Describe alternatives you've considered**
Maybe No.
