### ISSUE TITLE
[BUG] Self Hosting Resource Pack Issue

### ISSUE THREAD

**Issue by nuttyNaoko** [LoneDev6/ItemsAdder#580]
**Describe the bug**
I've been enjoying adding new items to the server but having to reupload it every time is a massive pain. I wanted to try the self host but i've been encountering issues. Here is some more context for the situation:

I have my main PC where i play games and do everything on. I have a second computer running Ubuntu Server and is online 24/7. I host it myself. This server is as you might expect, on the same network as my main PC. It has a local IP adress of `192.168.0.50`
The server works correctly since i am able to join using my numerical IP which has a domain name attached.
My own PC has a local IP adress of `192.168.0.75`

The wiki explains that you should leave the config on default settings if you are testing it on your own pc, in other words the server will go look for the pack in it's own plugin folder. I did change the port to `35566` and made sure it's open in the router settings. I have also tried using the actual server IP players use to join the server in the `config.yml`, no luck there either.

**To Reproduce**
1. **Go to** 'Simply installing the plugin and changing the port in the config to match the set one on the router'
2. **Click on** 'Restart server as reloading the config doesn't seem to apply the network settings'
3. **Scroll down to** 'Join the server'
4. **See error**: 'An error occurred when enabling the resource pack, please contact an admin or disable the resource pack entirely'

**Expected behavior**
I expect the client to start downloading the pack but it stays stuck on 'Making Request 100%' 

**Screenshots**
![image](https://user-images.githubusercontent.com/61063450/104126794-dde90800-535e-11eb-8d6a-56894a4471c7.png)

**Info (please complete the following information):**
 - **Server version**: Paper 1.16.4
 - **Client version**: Tried Vanilla 1.16.4, Fabric 1.16.4, Optifine 1.16.4. None work
 - **Plugin version**: 2.1.23

**Additional context**
The console does say that it started the webserver on the specified IP, and it said this in both, `127.0.0.1` and the numerical server IP. Tried browsing to `192.168.0.50:35566/pack.zip` and it just keeps loading, it's timing out.

```
metrics: true
resource-pack:
  apply-on-join: true
  kick-player-on-decline: false
  kick-player-on-fail: false
  delay-ticks: 1
  title:
    enabled: true
  self-host:
    enabled: true
    server-ip: 94.***.**.152
    pack-port: 35566
  external-host:
    enabled: false
    url: https://www.dropbox.com/s/***************/pack.zip?dl=1
```

I've been asking around on the discord for other people's configs who host their server somewhere else than their home. I have received 2 copies of a config and they both used the actual server's IP address.

I am sure this is a network issue since uploading the pack to dropbox works almost flawlessly. I'm still having issues where the pack seems to download the pack twice, but that's better to discuss in another issue.

I'm also getting this message in the console: not sure what this means, I have not found any config files that allow me to change or configure this. `[ItemsAdder] Failed to get username for: 498074`
@LoneDev6
